### ISSUE TITLE
### 1. **Issue: Add Functionality to Create a New Book**

### ISSUE THREAD

**Issue by ajinkyabridgelabz** [ajinkyabridgelabz/online-library-management-system#1]
**Description**:
Implement the backend functionality to support the creation of new books in the library. This involves 
creating a new book entity, a service to manage CRUD operations for the book, and a controller to handle 
web requests.

**Tasks**:
- [x] Define a `Book` entity with attributes such as `id`, `title`, `author`, `genre`, `isbn`, 
`publishedDate`, etc.
- [x] Create a `BookService` with a method `createBook(Book book)`.
- [x] Implement a `BookController` with a POST endpoint `/books` to add a new book.

**Comment by ajinkyabridgelabz** [comment]
Please develop this functionality and use ArrayList as a database.

**Comment by Mayurp375** [comment]
i added feature
