### ISSUE TITLE
### 2. **Issue: Design the Book Listing Page**

### ISSUE THREAD

**Issue by ajinkyabridgelabz** [ajinkyabridgelabz/online-library-management-system#2]
**Description**:
Design a page to list all the books available in the library. The list should provide essential details 
like the title, author, and genre.

**Tasks**:
- [ ] Implement a method `getAllBooks()` in `BookService`.
- [ ] In `BookController`, create a GET endpoint `/books` to fetch and display all books.

- [ ] Add pagination support if there are a lot of books. (Extra)

**Comment by ajinkyabridgelabz** [comment]
Pranali do this only after the work of mayur is completed

**Comment by pranalikubade** [comment]
Resolved Issue

**Comment by pranalikubade** [comment]
Resolved Issue
